services:
  - type: web
    name: ocr-api
    env: python
    region: singapore  
    plan: free  
    buildCommand: |
      apt-get update && 
      apt-get install -y tesseract-ocr tesseract-ocr-khm poppler-utils && 
      pip install --upgrade pip && 
      pip install -r requirements_api.txt
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 api:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
    healthCheckPath: /api/health